name: trello_clone_appwrite
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  appflowy_board: ^0.1.0
  appwrite: ^9.0.0
  auto_route: ^7.3.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.18.6
  flutter_svg: ^2.0.6
  fluttertoast: ^8.2.2
  hooks_riverpod: ^2.3.6
  logger: ^1.3.0
  responsive_builder: ^0.7.0
  riverpod_annotation: ^2.1.1
  velocity_x: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3
  auto_route_generator: ^7.1.1

flutter:
  uses-material-design: true
