name: trello_clone_appwrite
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  appwrite: ^9.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  responsive_builder: ^0.7.0
  velocity_x: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
